### ISSUE TITLE
Error when importing `SimpleProblem` and `SimpleObjective`

### ISSUE THREAD

**Issue by BenWinchester** [FraunhoferIWES/iwopy#12]
**Describe the bug**
An `ImportError` occurs when importing the `SimpleProblem` or `SimpleObjective` classes.

**To Reproduce**
- Create an anaconda environment (or Python installation) initially without the `iwopy` package installed,
- Install the package:
  ```bash
  python -m pip install iwopy
  ```
- Follow the instructions in `v0.1.6` of the documentation [here](https://fraunhoferiwes.github.io/iwopy.docs/notebooks/simple_function.html) for a Simple Function minimisation;
- Observe the error:

_Traceback:_
```bash
(testground) bewinche@penguin:~/modelling/reviewing/iwopy$ python -u -m pip freeze | grep "iwopy"
iwopy==0.1.5
(testground) bewinche@penguin:~/modelling/reviewing/iwopy$ python
Python 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from iwopy import SimpleProblem, SimpleObjective
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bewinche/modelling/reviewing/iwopy/iwopy/__init__.py", line 12, in <module>
    from . import interfaces
  File "/home/bewinche/modelling/reviewing/iwopy/iwopy/interfaces/__init__.py", line 2, in <module>
    from . import pymoo
  File "/home/bewinche/modelling/reviewing/iwopy/iwopy/interfaces/pymoo/__init__.py", line 1, in <module>
    from .optimizer import Optimizer_pymoo, DefaultCallback
  File "/home/bewinche/modelling/reviewing/iwopy/iwopy/interfaces/pymoo/optimizer.py", line 5, in <module>
    from .problem import SingleObjProblem, MultiObjProblem
  File "/home/bewinche/modelling/reviewing/iwopy/iwopy/interfaces/pymoo/problem.py", line 4, in <module>
    from .imports import check_import, Problem, Real, Integer
ImportError: cannot import name 'Real' from 'iwopy.interfaces.pymoo.imports' (/home/bewinche/modelling/reviewing/iwopy/iwopy/interfaces/pymoo/imports.py)
>>> 
```

**Expected behavior**
A user should be able to follow the instructions without encountering an error.

**Desktop (please complete the following information):**
 - OS: Debian 11.6

**Additional context**
This was identified as part of [the review](https://github.com/openjournals/joss-reviews/issues/6014) for the JOSS.

**Comment by StewMH** [comment]
Confirming that I see the same issue when trying to review the code.

**Comment by SchmJo** [comment]
Thanks for the bug report. It seems that you are mixing conda and pip installations, is that possible? The installation via conda should be done by `conda install -c conda-forge iwopy`, see the [documentation](https://fraunhoferiwes.github.io/iwopy.docs/installation.html).

My local version is a pure pip installation from the local repo clone (`pip install -e .` from the directory), and I cannot reproduce this. I will try again from the conda-forge installation.

**Comment by SchmJo** [comment]
Sorry, I can now indeed reprodce this for a fresh install -  for all installation approaches. I will try to figure out what is happening here.

**Comment by SchmJo** [comment]
Now it should show a message 
```console
Module 'pymoo.core.callback' not found, maybe try 'pip install pymoo'
```
If you then follow that suggestion, it should run smoothly

**Comment by BenWinchester** [comment]
Hi @SchmJo ,

It looks like this message is now popping up, telling the user that, to run the examples, they need to install `pygmo`/`pymoo`:
```python
>>> solver = Optimizer_pygmo(
...     problem,
...     problem_pars=dict(),
...     algo_pars=dict(type="ipopt", tol=1e-4),
... )
Loading pygmo
Traceback (most recent call last):
  File "/media/ben/E2A2F87FA2F8598D/Users/bened/PhD Synced/Reviewing/iwopy/iwopy/utils/load.py", line 27, in import_module
    return importlib.import_module(name, package)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pygmo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/ben/E2A2F87FA2F8598D/Users/bened/PhD Synced/Reviewing/iwopy/iwopy/interfaces/pygmo/optimizer.py", line 50, in __init__
    imports.load()
  File "/media/ben/E2A2F87FA2F8598D/Users/bened/PhD Synced/Reviewing/iwopy/iwopy/interfaces/pygmo/imports.py", line 27, in load
    pygmo = import_module("pygmo", hint="pip install pygmo")
  File "/media/ben/E2A2F87FA2F8598D/Users/bened/PhD Synced/Reviewing/iwopy/iwopy/utils/load.py", line 31, in import_module
    raise ModuleNotFoundError(f"Module '{mdl}' not found, maybe try '{hint}'")
ModuleNotFoundError: Module 'pygmo' not found, maybe try 'pip install pygmo'
```

In the review for the Journal of Open-Source Software, there's a requirement which is
> [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.

Whilst this pop-up to the user does work, I think it would be good to have, perhaps in the `README.md` or even in the test documentation, a list of dependencies that need to be installed in order for a user to run the package. As it is, the automated dependencies that come with `iwopy` don't let you run the tests, and they're not really documented (other than in this issue as far as I can tell).

**Comment by SchmJo** [comment]
@BenWinchester can we close this issue, considering the recent additions here: https://github.com/openjournals/joss-reviews/issues/6014#issuecomment-2137820074

**Comment by BenWinchester** [comment]
@SchmJo , yes! Feel free to close to the issue :smiley:
(Apologies for the delay, I'm currently travelling with limited access to a reliable and fast internet connection.)
