### ISSUE TITLE
Add multi-objective capabilities

### ISSUE THREAD

**Issue by SchmJo** [FraunhoferIWES/iwopy#8]
Pymoo has a strong multi-objective solver, NSGA2. We need an example that successfully runs it demonstrates how to handle Pareto front results

**Comment by SchmJo** [comment]
@albertoIWES maybe this is interesting for you, will be developed in branch [8-add-multi-objective-capabilities](https://github.com/FraunhoferIWES/iwopy/tree/8-add-multi-objective-capabilities)

**Comment by albertoIWES** [comment]
Thanks for letting me know! I'll check it out in the next days to see what's in 👍

________________________________

**Comment by SchmJo** [comment]
done with release v0.1.3
